### ISSUE TITLE
Updates needed for gazebo 9 compatibility

### ISSUE THREAD

**Issue by tfoote** [ros-simulation/gazebo_radar_plugin#3]
```
[ 96%] Built target gtest_main
In file included from /tmp/testws/src/gazebo_radar_plugin/src/ModeCRadarPlugin.cc:18:0:
/tmp/testws/src/gazebo_radar_plugin/include/gazebo_radar_plugin/ModeCRadarPlugin.hh:26:31: fatal error: gazebo/math/Pose.hh: No such file or directory
compilation terminated.
```

Need to switch to ignition math for gazebo9t

**Comment by salahkhan94** [comment]
Any update on this? Seeing this error on Gazebo 9 `fatal error: gazebo/math/Pose.hh: No such file or directory`

**Comment by tfoote** [comment]
We're not actively using this a PR to update it to use the ignition math libraries would be appreciated.

**Comment by Sarath18** [comment]
Appropriate changes have been made in PR #7 to make it compatible with Gazebo 9. These changes can be on a different `gazebo9` branch.

**Comment by tfoote** [comment]
Since gazebo9 is newer I instead moved master forward to the new API and created a gazebo7 branch for older users.

**Comment by Rochu96** [comment]
hey I am facing a similar issue i have a gazebo 11 version , what you are suggesting here?, should i chnage the verison to 7/9 or what?
