### ISSUE TITLE
@tfoote Thanks, i used as it mention am facing with error

### ISSUE THREAD

**Issue by gnykumar** [ros-simulation/gazebo_radar_plugin#6]
Unpause physics service call failed: unable to connect to service: [Errno 104] Connection reset by peer
Segmentation fault (core dumped)

Please let me know is anyone used this plugin already and working

_Originally posted by @gnykumar in https://github.com/ros-simulation/gazebo_radar_plugin/issues/4#issuecomment-444097798_

**Comment by gnykumar** [comment]
@tfoote
Sensor type ="logical_camera" is not working with libModeCRadarPlugin.so, gazebo process die with error i mentioned above.

Sensor type="radar" doesn't give any data with libModeCRadarPlugin, but gazebo is just running

**Comment by tfoote** [comment]
Please use issue trackers for bugs, enhancements, and development feature requests and ask for help on https://answers.ros.org

Guidelines for asking questions can be found at: https://wiki.ros.org/Support which include suggestions for what sort of details to include to communicate how to reproduce your problem. Without being able to reproduce your problem it's very hard to help you. The easier you make it to help you the more likely you are to get help.
